// Generated by the Kof compiler — KofJS runtime. Do not edit.
// Reachability-based content: only what the program reaches.
// kof:seeds kofArrayGet,kofArraySet,kofD2I,kofListAdd,kofListGet,kofListNew,kofListSize,kofMathSqrt,kofPrintln,kofTimeInterval,kofUiAudioNew,kofUiAudioPause,kofUiAudioPlay,kofUiAudioSetSrc,kofUiButtonNewAction,kofUiCanvasArc,kofUiCanvasBeginPath,kofUiCanvasClosePath,kofUiCanvasFill,kofUiCanvasLineTo,kofUiCanvasMoveTo,kofUiCanvasNew,kofUiCanvasRestore,kofUiCanvasSave,kofUiCanvasSetFill,kofUiCanvasSetGlobalAlpha,kofUiCanvasSetLineWidth,kofUiCanvasSetStroke,kofUiCanvasStroke,kofUiCanvasTransform,kofUiColumnNew,kofUiLabelNew,kofUiRowNew,kofUiWidgetOn,kofUiWindowBind,kofUiWindowNew,kofUiWindowSetTitle,kofUiWindowShow
// kof:units 90/774

// KofJS core runtime — platform-neutral helpers.
// Generated by the Kof compiler (KofJS backend).
// This module is not a VM: it only provides operations that
// JavaScript does not represent directly.

// #104: kof_platform só existe no host GraalJS; shim fora dele
// (Node/browser) troca ReferenceError por erro claro (#104).
if (!globalThis.kof_platform) {
    globalThis.kof_platform = new Proxy({
        print(x) { console.log(String(x)); }
    }, {
        get(t, prop) {
            if (prop in t) return t[prop];
            return function () {
                throw new Error("kof_platform." + String(prop)
                        + ": not available outside the Kof JS host");
            };
        }
    });
}

if (typeof document === "undefined") {
    function kofMakeEl(tag) {
        const attrs = {};
        const el = {
            tagName: String(tag).toUpperCase(),
            id: null,
            className: "",
            textContent: "",
            value: "",
            checked: false,
            readOnly: false,
            disabled: false,
            selectedIndex: -1,
            href: "",
            target: "",
            rel: "",
            src: "",
            alt: "",
            width: 0,
            height: 0,
            type: "",
            placeholder: "",
            children: [],
            parentNode: null,
            style: {},
            dataset: {},
            _attrs: attrs,
            classList: {
                _set: new Set(),
                add(cls) { this._set.add(cls); },
                remove(cls) { this._set.delete(cls); },
                toggle(cls) { if (this._set.has(cls)) { this._set.delete(cls); return false; } this._set.add(cls); return true; },
                contains(cls) { return this._set.has(cls); }
            },
            setAttribute(name, value) {
                attrs[String(name)] = String(value);
                if (name === "id") el.id = String(value);
                else if (name === "class") el.className = String(value);
                else if (name === "width") el.width = parseInt(value, 10) || 0;
                else if (name === "height") el.height = parseInt(value, 10) || 0;
            },
            getAttribute(name) {
                if (name === "id") return el.id;
                if (name === "class") return el.className;
                if (name === "width") return el.width;
                if (name === "height") return el.height;
                return Object.prototype.hasOwnProperty.call(attrs, name) ? attrs[name] : null;
            },
            hasAttribute(name) { return el.getAttribute(name) !== null; },
            removeAttribute(name) { delete attrs[name]; },
            querySelector(sel) {
                const want = String(sel).toUpperCase();
                const stack = el.children.slice();
                while (stack.length > 0) {
                    const n = stack.shift();
                    if (n.tagName === want) return n;
                    if (n.children) stack.push.apply(stack, n.children);
                }
                return null;
            },
            querySelectorAll(sel) {
                const want = String(sel).toUpperCase();
                const found = [];
                const stack = el.children.slice();
                while (stack.length > 0) {
                    const n = stack.shift();
                    if (n.tagName === want) found.push(n);
                    if (n.children) stack.push.apply(stack, n.children);
                }
                return found;
            },
            appendChild(child) {
                if (child && child.parentNode) child.parentNode.removeChild(child);
                child.parentNode = el;
                el.children.push(child);
                return child;
            },
            insertBefore(child, ref) {
                if (child && child.parentNode) child.parentNode.removeChild(child);
                child.parentNode = el;
                const i = el.children.indexOf(ref);
                if (i < 0) el.children.push(child);
                else el.children.splice(i, 0, child);
                return child;
            },
            removeChild(child) {
                const i = el.children.indexOf(child);
                if (i >= 0) { el.children.splice(i, 1); child.parentNode = null; }
                return child;
            },
            remove() { if (el.parentNode) el.parentNode.removeChild(el); },
            focus() {},
            blur() {},
            click() {
                const hs = (el._handlers && el._handlers.click) || [];
                for (const fn of hs) fn({ target: el, preventDefault() {}, stopPropagation() {} });
            },
            getContext(type) {
                if (type !== "2d") return null;
                return {
                    fillStyle: "#000", strokeStyle: "#000", lineWidth: 1,
                    globalAlpha: 1, font: "10px sans-serif",
                    textAlign: "left", textBaseline: "alphabetic",
                    beginPath() {}, closePath() {}, moveTo() {}, lineTo() {},
                    arc() {}, fill() {}, stroke() {}, clearRect() {},
                    fillRect() {}, strokeRect() {}, rect() {},
                    save() {}, restore() {}, translate() {}, rotate() {}, scale() {},
                    transform() {}, setTransform() {},
                    fillText() {}, strokeText() {},
                    measureText(text) { return { width: String(text).length * 6 }; },
                    drawImage() {},
                    createLinearGradient() { return { addColorStop() {} }; }
                };
            },
            addEventListener(type, fn) { el._handlers = el._handlers || {}; (el._handlers[type] = el._handlers[type] || []).push(fn); },
            removeEventListener(type, fn) {
                const hs = el._handlers && el._handlers[type];
                if (!hs) return;
                const i = hs.indexOf(fn);
                if (i >= 0) hs.splice(i, 1);
            }
        };
        Object.defineProperty(el, "options", {
            get() { return el.children.filter(function (c) { return c.tagName === "OPTION"; }); },
            configurable: true
        });
        Object.defineProperty(el, "firstChild", {
            get() { return el.children.length > 0 ? el.children[0] : null; },
            configurable: true
        });
        Object.defineProperty(el, "innerHTML", {
            get() { return ""; },
            set(v) { if (v === "") { el.children.length = 0; } },
            configurable: true
        });
        return el;
    }
    const kofRoot = kofMakeEl("div");
    kofRoot.id = "kof-root";
    const kofElements = { "kof-root": kofRoot };
    const kofHead = kofMakeEl("head");
    const kofHtml = kofMakeEl("html");
    kofHtml.appendChild(kofHead);
    globalThis.document = {
        title: "",
        head: kofHead,
        body: kofRoot,
        documentElement: kofHtml,
        createElement(tag) { return kofMakeEl(tag); },
        createElementNS(ns, tag) { return kofMakeEl(tag); },
        createTextNode(text) { const t = kofMakeEl("#text"); t.textContent = String(text); return t; },
        getElementById(id) { return kofElements[id] || null; },
        querySelector(sel) { return kofRoot.querySelector(sel); },
        querySelectorAll(sel) { return kofRoot.querySelectorAll(sel); }
    };
    globalThis.window = globalThis;
    globalThis.__kofRegisterElement = function (id, el) { kofElements[id] = el; };
}

function kofEscapeHtml(s) {
    return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;")
            .replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function kofSerialize(node) {
    if (!node) return "";
    const tag = (node.tagName ? node.tagName.toLowerCase() : "div");
    let attrs = "";
    if (node.id) attrs += ' id="' + kofEscapeHtml(node.id) + '"';
    if (node.className) attrs += ' class="' + kofEscapeHtml(node.className) + '"';
    if (node.src) attrs += ' src="' + kofEscapeHtml(node.src) + '"';
    const kids = Array.from(node.children || []);
    const inner = kids.map(kofSerialize).join("");
    if (tag === "hr" || tag === "iframe" || tag === "br" || tag === "img") {
        return "<" + tag + attrs + ">";
    }
    const content = inner.length > 0 ? inner : kofEscapeHtml(node.textContent || "");
    return "<" + tag + attrs + ">" + content + "</" + tag + ">";
}

export function kofUiSerializeHtml() {
    const root = document.getElementById("kof-root");
    if (!root) return "";
    const html = "<!DOCTYPE html>\n<html>\n<head>\n<meta charset=\"utf-8\">\n"
            + "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, viewport-fit=cover\">\n"
            + "<title>" + kofEscapeHtml(document.title || "Kof") + "</title>\n"
            + "</head>\n<body>\n" + kofSerialize(root) + "\n</body>\n</html>\n";
    globalThis.kof__uiRootHtml = html;
    return html;
}

export function kofPrintln(x) {
    console.log(x);
}

// D-NULL-INTENT (#278): Boolean.valueOf(Z) no JS — normaliza
// truthy/falsy num true/false estrito, mas PRESERVA null (Bool?
// genuino de Map.get/put/remove agora carrega ausência real; o
// ternário cru `x ? true : false` colapsava null -> false,
// apagando a ausência no println/String.valueOf).
export function kofArrayGet(array, index) {
    if (index < 0 || index >= array.length) {
        throw new Error("Array index out of bounds: " + index + " (length " + array.length + ")");
    }
    return array[index];
}

export function kofArraySet(array, index, value, kind) {
    if (index < 0 || index >= array.length) {
        throw new Error("Array index out of bounds: " + index + " (length " + array.length + ")");
    }
    // §184/§187: narrow to the element width on write, like the
    // JVM (i2b/i2s/i2c), Native (mask) and Script targets.
    // kind: 1 = byte (i2b), 2 = short (i2s), 3 = char (i2c), 0 = none.
    if (kind === 1) {
        array[index] = (value << 24) >> 24;
    } else if (kind === 2) {
        array[index] = (value << 16) >> 16;
    } else if (kind === 3) {
        array[index] = value & 0xFFFF;
    } else {
        array[index] = value;
    }
}

// hashCode de valor Kof: espelha o Objects.hashCode/record JVM.
// primitivos numéricos → int32 (wrap), String → algoritmo Java,
// record → hashCode() sintético, senão → hash de String(valor).
export function kofUiWindowNew(title) {
    if (typeof document === "undefined") {
        return -1;
    }
    kofUiInjectTheme();
    const root = document.getElementById("kof-root");
    if (!root) {
        return -1;
    }
    if (typeof window.__kofWindows === "undefined") {
        window.__kofWindows = {};
    }
    const id = Object.keys(window.__kofWindows).length + 1;
    const winEl = document.createElement("div");
    winEl.className = "kof-window";
    window.__kofWindows[id] = winEl;
    document.title = title;
    root.appendChild(winEl);
    return id;
}

// Kof UI theme — the same Dracula/VSCode aesthetic in every host
// (browser, webview, KofWebHost): one Kof program, one look.
function kofUiInjectTheme() {
    if (typeof document === "undefined") return;
    if (document.getElementById("kof-theme")) return;
    const style = document.createElement("style");
    style.id = "kof-theme";
    style.textContent = [
        ":root { --bg:#282a36; --fg:#f8f8f2; --panel:#21222c; --border:#2e303e;",
        "  --hover:#2e303e; --accent:#8be9fd; --dim:#6272a4; --output:#50fa7b; }",
        "html, body { margin:0; height:100%; overflow:hidden; }",
        "body { background:var(--bg); color:var(--fg); font-family:",
        '  "Cascadia Code", "Fira Code", Consolas, Menlo, monospace; }',
        ".kof-label { color:var(--output); font-size:13px; line-height:1.5;",
        "  white-space:pre-wrap; padding:2px 0; }",
        // issues #75/#76 (10/09): o runtime AO VIVO não tinha NENHUMA
        // regra p/ Column/Row (renderizavam divs crus, sem flex) nem
        // p/ Button/Input/Textarea/Select (controles nativos crus).
        // Espelha o exportador ESTÁTICO (JsArtifactWriter) no MESMO
        // vocabulário de var(--…) do tema — paridade vivo↔estático.
        ".kof-column { display:flex; flex-direction:column; gap:8px; }",
        ".kof-row { display:flex; flex-direction:row; flex-wrap:wrap;",
        "  gap:8px; align-items:flex-start; }",
        ".kof-button { font-size:13px; padding:6px 14px; cursor:pointer;",
        "  background:var(--panel); color:var(--fg);",
        "  border:1px solid var(--border); border-radius:6px; }",
        ".kof-button:hover { background:var(--hover); }",
        ".kof-input, .kof-textarea, .kof-select { font-size:13px; padding:6px 10px;",
        "  background:var(--panel); color:var(--fg); font-family:inherit;",
        "  border:1px solid var(--border); border-radius:6px; }",
        ".kof-input { width:100%; }",
        ".kof-view { box-sizing:border-box; }",
        ".kof-window { box-sizing:border-box; padding:16px; border-radius:8px;",
        "  border:1px solid var(--border); background:var(--bg);",
        "  display:flex; flex-direction:column; gap:8px; }"
    ].join("\n");
    (document.head || document.documentElement).appendChild(style);
}

export function kofUiWindowSetTitle(window, title) {
    if (typeof document !== "undefined") {
        document.title = title;
    }
}

export function kofUiWindowBind(win, label) {
    if (typeof document === "undefined") {
        return;
    }
    const winEl = globalThis.window && globalThis.window.__kofWindows
            && globalThis.window.__kofWindows[win];
    if (!winEl) return;
    // Component Core: a component binds under the window and mounts
    // (view + onMount) — lifecycle is automatic.
    const comp = kofUiComponents.get(label);
    if (comp) {
        if (comp.el) winEl.appendChild(comp.el);
        kofUiComponentMount(label);
        return;
    }
    const nodes = globalThis.window && globalThis.window.__kofNodes;
    const node = nodes && nodes[label];
    if (node) {
        winEl.appendChild(node);
    }
}

export function kofUiWindowShow(window) {
    kofUiSerializeHtml();
}
// §104c: igualdade de conteúdo em coleções JS. Primitivos/String
// resolvem no caminho nativo (SameValueZero) — o fallback pega
// objeto Kof (record) com .equals(other) sintético → 1/0, ou
// List/Set por conteúdo (#518). Assim `listOf(p1).contains(p2)`,
// `setOf/mapOf` por conteúdo batem com o oracle JVM sem alterar
// o armazenamento nem o kofFormat.
// ── Component Core (docs/ui/architecture.md) ─────────────
// A UI is a tree of components. A Component node carries: identity,
// state (Int), a view builder, lifecycle hooks, effects (auto-cleaned)
// and events. Rendering is KofJS; the framework (not the widget)
// owns the tree, the render schedule and the lifecycle.
const kofUiComponents = new Map();
let kofNodeSeq = 0;
let kofUiCurrentComponent = null;
const KOF_UI_EV = {
    click: "click", dblclick: "dblclick", mousedown: "mousedown",
    mouseup: "mouseup", mousemove: "mousemove", mouseenter: "mouseenter",
    mouseleave: "mouseleave", wheel: "wheel", keydown: "keydown",
    keyup: "keyup", focus: "focus", blur: "blur", input: "input", change: "change"
};

function kofUiIsNode(id) {
    return window.__kofNodes && Object.prototype.hasOwnProperty.call(window.__kofNodes, id);
}
function kofUiPruneNode(n) {
    // §300 prune applied to a DOM node (used by root-kind reuse where
    // the root handle must survive). Every registry key that maps to
    // the node dies with it — D-UI-DIFF (B) aliases the fresh root
    // handle onto the old node, so a node can have TWO keys and the
    // old single-key `break` would leak the alias forever.
    if (!n) return;
    const q = [n];
    while (q.length > 0) {
        const x = q.shift();
        if (!x || x._kofGone) continue;
        for (const k of Array.from(x.children || [])) q.push(k);
        if (x.parentNode) x.parentNode.removeChild(x);
        x._kofGone = true;
        for (const key in window.__kofNodes) {
            if (window.__kofNodes[key] === x) {
                delete window.__kofNodes[key];
                // §300: the action table is a SECOND global keyed by
                // the same handle — without this the discarded
                // Button action (and its closure) stays reachable
                // forever. __kofFormSubmits is a third (Form).
                if (window.__kofActions) delete window.__kofActions[key];
                if (window.__kofFormSubmits) delete window.__kofFormSubmits[key];
            }
        }
    }
}
function kofUiRemoveSubtree(rootId) {
    // remove the DOM subtree of a widget id and prune the registry
    if (!kofUiIsNode(rootId)) return;
    kofUiPruneNode(window.__kofNodes[rootId]);
}

function kofUiRunFn(fn) {
    // a Kof lambda compiles to a class with an invoke() method;
    // plain functions pass through.
    return fn && typeof fn.invoke === "function" ? fn.invoke.bind(fn) : fn;
}

function kofUiOnDom(node, type, fn) {
    // single funnel for widget-node DOM listeners so D-UI-DIFF (B)
    // reuse can MOVE them from the discarded node to the survivor
    // (removeEventListener needs the exact reference). Component
    // wrapper (.on) listeners live on the component div, never on a
    // reused widget root, and stay outside this funnel.
    if (!node || typeof node.addEventListener !== "function") return;
    node._kofDomListeners = node._kofDomListeners || [];
    node._kofDomListeners.push({ t: type, f: fn });
    node.addEventListener(type, fn);
}

function kofUiCopyValueProps(oldEl, newEl) {
    // (B) contract, "value-bearing properties": attributes (style
    // strings, class, widget props), the CSSOM object the runtime
    // writes (n.style.X = ...), text on a leaf, and the direct
    // properties the widget families set. User input wins over an
    // absent declaration: `value`/`checked` are copied ONLY when the
    // fresh node carries a non-default value.
    const names = oldEl.getAttributeNames
        ? Array.from(new Set(Object.keys(newEl._attrs || {}).concat(newEl.getAttributeNames())))
        : Object.keys(newEl._attrs || {});
    for (const a of names) {
        if (a === "value" || a === "checked") continue;
        const v = newEl.getAttribute(a);
        if (v !== null) oldEl.setAttribute(a, v);
    }
    for (const k in oldEl.style) delete oldEl.style[k];
    for (const k in (newEl.style || {})) oldEl.style[k] = newEl.style[k];
    for (const k in (newEl.dataset || {})) oldEl.dataset[k] = newEl.dataset[k];
    const kids = newEl.children || [];
    if (kids.length === 0 && typeof newEl.textContent === "string") {
        oldEl.textContent = newEl.textContent;
    }
    if (typeof newEl.value === "string" && newEl.value !== "") oldEl.value = newEl.value;
    if (newEl.checked) oldEl.checked = true;
}

function kofUiRehomeWidgetHandlers(oldEl, oldId, newEl) {
    // (B) detail: handlers registered via kofUiWidgetOn close over
    // the handle of the node they were set on — the fresh node dies,
    // so their dispatch is RE-REGISTERED on the surviving handle
    // instead of moving the closure (which would dispatch through a
    // dead id). Wrapper fns carry a marker and are skipped when the
    // raw DOM listeners move over in kofUiReuseRoot.
    const hm = newEl._kofHandlers || {};
    for (const domType in hm) {
        for (const h of hm[domType]) {
            kofUiWidgetOnHandle(oldId, domType, h);
        }
    }
}

function kofUiReuseRoot(oldEl, newEl, oldId, newId) {
    // D-UI-DIFF (B): same root kind across renders — the OLD node
    // (and its focus/caret/scroll) survives; the fresh node's
    // properties and children migrate onto it and it is discarded.
    // The OLD handle keeps its identity and stays the ONLY
    // __kofNodes key for the node (alias-free: the §300 registry
    // bound holds), so the per-handle dispatch tables are re-homed
    // from newId to oldId.
    for (const kid of Array.from(oldEl.children || [])) kofUiPruneNode(kid);
    for (const l of oldEl._kofDomListeners || []) {
        if (oldEl.removeEventListener) oldEl.removeEventListener(l.t, l.f);
    }
    oldEl._kofDomListeners = [];
    oldEl._kofHandlers = {};
    for (const k of oldEl._kofStaleForms || []) {
        if (window.__kofFormSubmits) delete window.__kofFormSubmits[k];
    }
    oldEl._kofStaleForms = [];
    kofUiCopyValueProps(oldEl, newEl);
    for (const kid of Array.from(newEl.children || [])) oldEl.appendChild(kid);
    kofUiRehomeWidgetHandlers(oldEl, oldId, newEl);
    if (window.__kofActions && window.__kofActions[newId] !== undefined) {
        window.__kofActions[oldId] = window.__kofActions[newId];
        delete window.__kofActions[newId];
    }
    if (window.__kofFormSubmits && window.__kofFormSubmits[newId] !== undefined) {
        window.__kofFormSubmits[oldId] = window.__kofFormSubmits[newId];
        oldEl._kofStaleForms.push(newId);
    }
    for (const l of newEl._kofDomListeners || []) {
        if (l.f && l.f.__kofWidgetWrapper) continue;
        kofUiOnDom(oldEl, l.t, l.f);
    }
    newEl._kofGone = true;
    newEl._kofHandlers = undefined;
    newEl._kofDomListeners = undefined;
    if (newEl.parentNode) newEl.parentNode.removeChild(newEl);
    delete window.__kofNodes[newId];
}

function kofUiReportError(where, e) {
    // §266-filha: os catches deste módulo ENGOLIAM o throw do
    // código do usuário — view que crashava = UI vazia SEM NENHUMA
    // mensagem no console do browser (a lição do §266: o loop estava
    // errado, mas QUALQUER outro crash de view continuava silencioso
    // p/ UI e barulhento só headless). Mantém a resiliência (um
    // component quebrado não derruba os irmãos do flush) mas TORNA
    // O ERRO VISÍVEL: console.error com contexto + o throw original
    // (stack quando houver), espelhando o stderr do JVM/Script.
    const detail = e && (e.stack || e.message) ? (e.stack || e.message) : String(e);
    try {
        (console.error || console.log)("[kof] " + where + ": " + detail);
    } catch (ignored) {}
}

function kofUiRender(c) {
    // rebuild the component's child subtree: run the view builder
    // with the current state, then swap the fresh DOM in place.
    // (handle diffing is a Phase-9 optimization)
    let rootId = 0;
    const prevCtx = kofUiCurrentComponent;
    kofUiCurrentComponent = c;
    try {
        const v = kofUiRunFn(c.view);
        rootId = v ? v(c.state) : 0;
    } catch (e) {
        kofUiReportError("view render threw for component " + (c && c.name), e);
        rootId = 0;
    } finally {
        kofUiCurrentComponent = prevCtx;
    }
    if (c.el) {
        const oldEl = window.__kofNodes && window.__kofNodes[c.root];
        const rootEl = window.__kofNodes && window.__kofNodes[rootId];
        if (oldEl && rootEl && oldEl !== rootEl && c.root !== rootId
            && oldEl.tagName === rootEl.tagName) {
            // D-UI-DIFF (B): stable root kind → the old DOM node
            // survives (focus/caret/scroll preserved); the old root
            // handle keeps its identity. Different kind (or error
            // render) → rebuild + prune exactly as §300.
            kofUiReuseRoot(oldEl, rootEl, c.root, rootId);
            rootId = c.root;
        } else {
            if (c.root !== rootId) {
                // §300: the previous render's subtree must be pruned from
                // BOTH the DOM and __kofNodes (detaching only the root
                // leaked every old node — unbounded, silent).
                kofUiRemoveSubtree(c.root);
            }
            if (rootEl && rootEl.parentNode !== c.el) {
                c.el.appendChild(rootEl);
            }
        }
    }
    c.root = rootId;
}

function kofUiRunEffect(n, f) {
    let result;
    const prevCtx = kofUiCurrentComponent;
    kofUiCurrentComponent = n;
    try {
        result = f();
    } catch (e) {
        kofUiReportError("effect threw", e);
        result = null;
    } finally {
        kofUiCurrentComponent = prevCtx;
    }
    n.effects.push(result);
}

export function kofUiComponentMount(c) {
    const n = kofUiComponents.get(c);
    if (!n || n.mounted) return;
    n.mounted = true;
    // mount: (mount view) -> onMount() -> effects — deterministic
    if (n.view) kofUiRender(n);
    const om = kofUiRunFn(n.onMountFn);
    if (om) {
        const prevCtx = kofUiCurrentComponent;
        kofUiCurrentComponent = n;
        try { om(); } catch (e) { kofUiReportError("onMount threw", e); }
        finally { kofUiCurrentComponent = prevCtx; }
    }
    for (const f of n.effectFns) kofUiRunEffect(n, f);
}

export function kofUiWidgetOn(id, type, handler) {
    if (!type || !handler) return;
    const node = window.__kofNodes && window.__kofNodes[id];
    if (!node) return;
    kofUiWidgetOnHandle(id, KOF_UI_EV[type] || type, handler);
}

function kofUiWidgetOnHandle(id, domType, handler) {
    // domType already mapped through KOF_UI_EV; the wrapper carries
    // a marker so (B) reuse re-registers instead of moving it.
    const node = window.__kofNodes && window.__kofNodes[id];
    if (!node) return;
    node._kofHandlers = node._kofHandlers || {};
    const arr = node._kofHandlers[domType];
    if (arr) arr.push(handler);
    else node._kofHandlers[domType] = [handler];
    const wrapper = function (ev) {
        kofUiDispatchWidgetEvent(id, domType, ev);
    };
    wrapper.__kofWidgetWrapper = true;
    kofUiOnDom(node, domType, wrapper);
}
// ── Link ────────────────────────────────────────────
// ── Font ───────────────────────────────────────────
export function kofUiLabelNew(text) {
    if (typeof document === "undefined") {
        return -1;
    }
    const span = document.createElement("span");
    span.textContent = text;
    span.className = "kof-label";
    if (typeof window.__kofNodes === "undefined") {
        window.__kofNodes = {};
    }
    const id = ++kofNodeSeq;
    window.__kofNodes[id] = span;
    return id;
}

function kofUiCreateNode(tag, className) {
    if (typeof document === "undefined") {
        return -1;
    }
    const el = document.createElement(tag);
    el.className = className;
    if (typeof window.__kofNodes === "undefined") {
        window.__kofNodes = {};
    }
    const id = ++kofNodeSeq;
    window.__kofNodes[id] = el;
    return id;
}

function kofUiSetAction(id, action) {
    if (!action || typeof document === "undefined") {
        return;
    }
    window.__kofActions = window.__kofActions || {};
    window.__kofActions[id] = action;
    const node = window.__kofNodes[id];
    if (node) {
        kofUiOnDom(node, "click", function () {
            action.invoke();
        });
    }
}

export function kofUiButtonNewAction(text, action) {
    const id = kofUiCreateNode("button", "kof-button");
    if (id < 0) {
        return -1;
    }
    window.__kofNodes[id].textContent = text;
    kofUiSetAction(id, action);
    return id;
}

export function kofUiColumnNew(ids) {
    const id = kofUiCreateNode("div", "kof-column");
    if (id < 0) {
        return -1;
    }
    const node = window.__kofNodes[id];
    if (ids) {
        for (const childId of ids) {
            const child = window.__kofNodes[childId];
            if (child) {
                node.appendChild(child);
            }
        }
    }
    return id;
}

export function kofUiRowNew(ids) {
    const id = kofUiCreateNode("div", "kof-row");
    if (id < 0) {
        return -1;
    }
    const node = window.__kofNodes[id];
    if (ids) {
        for (const childId of ids) {
            const child = window.__kofNodes[childId];
            if (child) {
                node.appendChild(child);
            }
        }
    }
    return id;
}

export function kofUiCanvasNew(w, h) {
    if (typeof document === "undefined") return -1;
    const canvas = document.createElement("canvas");
    canvas.width = w;
    canvas.height = h;
    canvas.className = "kof-canvas";
    canvas.style.display = "block";
    const ctx = canvas.getContext("2d");
    if (typeof window.__kofNodes === "undefined") window.__kofNodes = {};
    const id = ++kofNodeSeq;
    window.__kofNodes[id] = canvas;
    window.__kofCanvasCtx = window.__kofCanvasCtx || {};
    window.__kofCanvasCtx[id] = ctx;
    // renderiza standalone: anexa ao root (w.bind(c) re-parenteia
    // para a janela — appendChild remove do pai anterior)
    const root = document.getElementById("kof-root");
    if (root) root.appendChild(canvas);
    return id;
}
export function kofUiCanvasBeginPath(id) {
    const ctx = window.__kofCanvasCtx && window.__kofCanvasCtx[id];
    if (ctx) ctx.beginPath();
}
export function kofUiCanvasClosePath(id) {
    const ctx = window.__kofCanvasCtx && window.__kofCanvasCtx[id];
    if (ctx) ctx.closePath();
}
export function kofUiCanvasMoveTo(id, x, y) {
    const ctx = window.__kofCanvasCtx && window.__kofCanvasCtx[id];
    if (ctx) ctx.moveTo(x, y);
}
export function kofUiCanvasLineTo(id, x, y) {
    const ctx = window.__kofCanvasCtx && window.__kofCanvasCtx[id];
    if (ctx) ctx.lineTo(x, y);
}
export function kofUiCanvasArc(id, x, y, r, startAngle, endAngle) {
    const ctx = window.__kofCanvasCtx && window.__kofCanvasCtx[id];
    if (ctx) ctx.arc(x, y, r, startAngle, endAngle);
}
export function kofUiCanvasFill(id) {
    const ctx = window.__kofCanvasCtx && window.__kofCanvasCtx[id];
    if (ctx) ctx.fill();
}
export function kofUiCanvasStroke(id) {
    const ctx = window.__kofCanvasCtx && window.__kofCanvasCtx[id];
    if (ctx) ctx.stroke();
}
export function kofUiCanvasSetFill(id, color) {
    const ctx = window.__kofCanvasCtx && window.__kofCanvasCtx[id];
    if (ctx) ctx.fillStyle = kofUiColorToCss(color);
}
export function kofUiCanvasSetStroke(id, color) {
    const ctx = window.__kofCanvasCtx && window.__kofCanvasCtx[id];
    if (ctx) ctx.strokeStyle = kofUiColorToCss(color);
}
export function kofUiCanvasSetLineWidth(id, w) {
    const ctx = window.__kofCanvasCtx && window.__kofCanvasCtx[id];
    if (ctx) ctx.lineWidth = w;
}
export function kofUiCanvasSave(id) {
    const ctx = window.__kofCanvasCtx && window.__kofCanvasCtx[id];
    if (ctx) ctx.save();
}
export function kofUiCanvasRestore(id) {
    const ctx = window.__kofCanvasCtx && window.__kofCanvasCtx[id];
    if (ctx) ctx.restore();
}
export function kofUiCanvasSetGlobalAlpha(id, alpha) {
    const ctx = window.__kofCanvasCtx && window.__kofCanvasCtx[id];
    if (ctx) ctx.globalAlpha = alpha;
}
export function kofUiCanvasTransform(id, a, b, c, d, e, f) {
    const ctx = window.__kofCanvasCtx && window.__kofCanvasCtx[id];
    if (ctx) ctx.transform(a, b, c, d, e, f);
}
export function kofUiAudioNew(src) {
    const id = kofUiCreateNode("audio", "kof-audio");
    if (id < 0) {
        return -1;
    }
    window.__kofNodes[id].src = src;
    return id;
}

export function kofUiAudioSetSrc(audio, src) {
    if (typeof document !== "undefined" && window.__kofNodes && window.__kofNodes[audio]) {
        window.__kofNodes[audio].src = src;
    }
}

export function kofUiAudioPlay(audio) {
    if (typeof document !== "undefined" && window.__kofNodes && window.__kofNodes[audio]
            && typeof window.__kofNodes[audio].play === "function") {
        window.__kofNodes[audio].play();
    }
}

export function kofUiAudioPause(audio) {
    if (typeof document !== "undefined" && window.__kofNodes && window.__kofNodes[audio]
            && typeof window.__kofNodes[audio].pause === "function") {
        window.__kofNodes[audio].pause();
    }
}
// ── Layout primitives (docs/ui/architecture.md §2.8) ──────
// CSS-first: the framework never computes pixel positions; each
// primitive maps to a flex/grid CSS pattern.
export function kofUiColorToCss(color) {
    const r = (color >>> 24) & 0xFF;
    const g = (color >>> 16) & 0xFF;
    const b = (color >>> 8) & 0xFF;
    const a = color & 0xFF;
    if (a === 255) {
        return "rgb(" + r + ", " + g + ", " + b + ")";
    }
    return "rgba(" + r + ", " + g + ", " + b + ", " + a + ")";
}

export function kofListNew() {
    return [];
}

export function kofListAdd(list, value) {
    list.push(value);
}

export function kofListGet(list, index) {
    if (index < 0 || index >= list.length) {
        throw new Error("Index out of bounds: " + index + " (size " + list.length + ")");
    }
    return list[index];
}

export function kofListSize(list) {
    return list.length;
}
// §103.1 (#103): decode<Map<String,T>> no JS — monta um Map
// real (o else dava objeto puro: m.size/m.get quebravam); com
// decoder, cada valor é bindado à classe.
// ── Web runtime (WEB001) — GraalJS HttpServer com handler invoke
// Handler lambda tem metodo invoke(); usamos Value para interop.
const kofTimeJobs = new Map();
const kofTimeSeq = { value: 0 };
function kofTimeRunJob(fn) {
    if (typeof fn.invoke === 'function') fn.invoke();
    else if (typeof fn === 'function') fn();
}
export function kofTimeInterval(ms, fn) {
    if (typeof setInterval === 'function') {
        return "n" + String(setInterval(() => kofTimeRunJob(fn), ms));
    }
    const id = "c" + (++kofTimeSeq.value);
    kofTimeJobs.set(id, { ms: ms, run: () => kofTimeRunJob(fn), next: Date.now() + ms });
    return id;
}
// ── kof.security (docs/stdlib/security.md §5) ────────────────────
// ── AES-256-GCM (SECN002 fechado 01/09) ───────────────────
// Puro JS (roda no GraalJS e no browser). Formato idêntico ao
// JVM/Native: aesgcm$<ivB64>$<ct||tagB64>, key 32 bytes (64 hex),
// IV 12 bytes aleatórios, tag 128-bit. S-box FIPS 197; GHASH/CTR
// NIST SP 800-38D. Validado byte-a-byte contra node:crypto e o
// vetor NIST (KofSecurityTest.aesGcmJsRoundTrip + paridade JVM).

    // ── kof.validation (STDLIB S12) — pontuação BR ─────────────
    // 11 dígitos => DDD.DDD.DDD-DD; 8 => DDDDD-DDDD; senão original
    // (null => null; nunca lança — face leniente da lane).
        // ── kof.math (STDLIB S1) — Int-only, paridade JVM/Native ─────
        export function kofMathSqrt(v) { return Math.sqrt(v); }

        // ── kof.strings (STDLIB S2a) — predicados de char ───────────

// kof.random (STDLIB S10a) — face não-críptográfica. Entropia do
// SO: kof_platform (SecureRandom no runner Node); no browser o
// proxy lança, cai em crypto.getRandomValues. bound<=0 -> 0
// (leniente — contrato do plano; security.randomInt lança).

// ── kof.rng (X8 fatia 1) — xorshift128 + splitmix32, 32-bit ──
// Estado default fixo (0,0,0,1): programa sem seed é determinístico.
// ── kof.math S1b.1 — Double puros (paridade JVM/Native) ─────
// Bool = 1/0 (chokepoint §93 cuida do ==true).
// ── §181 (13/09): casts Double/Float -> Int/Long SATURANTES
// (JLS 5.1.3 — NaN => 0, > MAX => MAX, < MIN => MIN). O
// Math.trunc cru dava 3e9 (fora do Int32), NaN e Infinity.
// Long = BigInt saturado (paridade 64-bit do §81).
export function kofD2I(v) {
    if (isNaN(v)) return 0;
    const t = Math.trunc(v);
    if (t > 2147483647) return 2147483647;
    if (t < -2147483648) return -2147483648;
    return t;
}
// ── §264: Double/Float → string no formato do JDK ─────────────
// Regra Double.toString: significante com round-trip mínimo,
// decimal quando -3 <= exp < 7, senão E±m sem leading-zero.
// Sempre ao menos um dígito fracionário (4 → "4.0").
// ── kof.buffer — Buffer(U8) (D-R3-BUFFER) no alvo JS ──────────
// Espelha KofRuntime$Buffer do JVM: um byte-container opaco. Nome
// interno (KofBufferBox) p/ não sombrear o `Buffer` global do Node.

// ── kof.net (STDLIB S8) ────────────────────────────────────────

// ── kof.uuid (STDLIB S3b / S3b.2) ──────────────────────────────
// v4: kof_platform.randomBytesHex (16 B) -> RFC 4122

        // ── kof.strings (STDLIB S3.2) — whitespace ──────────────────
// Fase 5 (docs/ui/architecture.md §2.5): target -> bubbles up the
// component tree (child -> parent). The handler receives a Kof
// Event with type + stopPropagation support.
function kofUiMakeEvent(domType, ev) {
    const raw = ev || null;
    return {
        stopped: false,
        // Kof accesses event kind as e.type() (a method call)
        type() { return domType; },
        stopPropagation() { this.stopped = true; },
        // UI006: key/value/x/y do DOM event real (null/vazio no
        // host mock e no emit sintético).
        key() {
            return raw && typeof raw.key === "string" ? raw.key : "";
        },
        value() {
            if (!raw) return "";
            const t = raw.target;
            return t && typeof t.value === "string" ? t.value : "";
        },
        x() { return raw && typeof raw.clientX === "number" ? raw.clientX : 0; },
        y() { return raw && typeof raw.clientY === "number" ? raw.clientY : 0; },
        // UI006 residual: alvo do evento como id do nó (fallback
        // tagName minúscula quando sem setId; "" fora do browser).
        target() {
            const t = raw && raw.target;
            if (!t) return "";
            return t.id ? String(t.id)
                    : (t.tagName ? t.tagName.toLowerCase() : "");
        },
        relatedTarget() {
            const t = raw && raw.relatedTarget;
            if (!t) return "";
            return t.id ? String(t.id)
                    : (t.tagName ? t.tagName.toLowerCase() : "");
        },
        // raw DOM event passthrough (null in the host mock)
        raw: raw
    };
}

// UI006: dispatch de widget DOM (fora da árvore de Component) —
// o handler recebe o kofEv construído do evento DOM real.
function kofUiDispatchWidgetEvent(id, domType, ev) {
    const node = window.__kofNodes && window.__kofNodes[id];
    if (!node) return;
    const h = node._kofHandlers && node._kofHandlers[domType];
    if (!h) return;
    const kofEv = kofUiMakeEvent(domType, ev);
    for (const fn of h) {
        try {
            if (typeof fn.invoke === "function") fn.invoke(kofEv);
            else fn(kofEv);
        } catch (e) {}
    }
}
